### ISSUE TITLE
Error with v4.5.1 and Buildcraft 7.0.8

### ISSUE THREAD

**Issue by NitroxydeX** [tcooc/AdditionalPipesBC#120]
After upgrading to BC7 and AP 4.5.1 I get this Error Message after Startup. removeErroringTileEntities did not fix the problem.

```
java.lang.NoSuchMethodError: buildcraft.transport.PipeTransportPower.receiveEnergy(Lnet/minecraftforge/common/util/ForgeDirection;I)I
	at buildcraft.additionalpipes.pipes.PipePowerTeleport.receiveEnergy(PipePowerTeleport.java:108)
	at buildcraft.transport.PipeTransportPower.receiveEnergy(PipeTransportPower.java:379)
	at buildcraft.transport.PipeTransportPower.updateEntity(PipeTransportPower.java:225)
	at buildcraft.transport.Pipe.updateEntity(Pipe.java:143)
	at buildcraft.transport.pipes.PipePowerWood.updateEntity(PipePowerWood.java:72)
	at buildcraft.transport.TileGenericPipe.func_145845_h(TileGenericPipe.java:385)
	at buildcraft.transport.TileGenericPipeCompat.func_145845_h(TileGenericPipeCompat.java:85)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by multiplemonomials** [comment]
This should be fixed in the latest version.  Can you try it and make sure it works?

**Comment by NitroxydeX** [comment]
Worked! Thanks a lot @multiplemonomials :3 :+1:

**Comment by multiplemonomials** [comment]
Actually, I was in discussion about this same issue on the forums at the same time.  Thanks for letting me know.
